import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MainHeader from "@/components/mainHeader";
import CategoryNavbar from "../../components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex-1 overflow-y-auto overflow-x-hidden max-h-100vh z-30">
          <MainHeader />
          <CategoryNavbar />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
